import type { Track } from "./types";

export const javascriptTrack: Track = {
  id: "javascript",
  title: "JavaScript",
  description: "Variables, functions, arrays, and conditionals — the fundamentals of JS.",
  color: "#f0db4f",
  levels: [
    {
      id: 1,
      title: "Variables",
      filename: "lesson1.js",
      difficulty: "easy",
      objective: 'Assign values to the variables so the program outputs "Hello World 42"',
      preview: ["Hello World 42"],
      codeLines: [
        "// Variables store data values",
        "let message = {{zone1}};",
        "let count = {{zone2}};",
        "",
        "console.log(message, count);",
      ],
      zones: [
        { id: "zone1", answer: '"Hello World"' },
        { id: "zone2", answer: "42" },
      ],
      blocks: [
        { id: "b1", code: '"Hello World"' },
        { id: "b2", code: "42" },
        { id: "b3", code: "true" },
        { id: "b4", code: "null" },
        { id: "b5", code: "[]" },
      ],
      wormIntro:
        "Hi! I'm Debug the worm! 🐛 Drag the correct values into the empty slots to assign the variables. Message should be a string, count should be a number!",
      wormCorrectAll: "Amazing! You assigned both variables correctly! Let's move to the next challenge! 🎉",
      concept: {
        summary: "let declares a variable that can hold any type of value.",
        details: [
          "A variable is just a named box for a value. `let message = \"Hello World\"` stores text (a string, always in quotes); `let count = 42` stores a number (no quotes).",
          "JavaScript doesn't make you declare a type up front — the same `let` works for strings, numbers, booleans, or anything else. That flexibility is convenient, but it also means typos like forgetting quotes around text are easy to make and won't be caught until the program runs.",
          "You'll also see `const` for variables that should never be reassigned after their first value, and old-style `var` (best avoided in modern code — it has confusing scoping rules `let`/`const` fixed).",
        ],
        example: 'const pi = 3.14; // const: value never changes\nlet score = 0;   // let: value will change later\nscore = score + 10;',
      },
    },
    {
      id: 2,
      title: "Functions",
      filename: "lesson2.js",
      objective: 'Complete the "add" function so it returns the sum of a and b (should output 10)',
      difficulty: "easy",
      preview: ["10"],
      codeLines: [
        "function add(a, b) {",
        "  return {{zone1}};",
        "}",
        "",
        "let result = add(3, 7);",
        "console.log(result); // 10",
      ],
      zones: [{ id: "zone1", answer: "a + b" }],
      blocks: [
        { id: "b1", code: "a + b" },
        { id: "b2", code: "a - b" },
        { id: "b3", code: "a * b" },
        { id: "b4", code: "a / b" },
      ],
      wormIntro:
        "This function should ADD two numbers together! Drag the expression that represents their sum into the return slot. What operation combines two values?",
      wormCorrectAll: "Perfect! a + b adds both parameters together! You're getting it! 🚀",
      concept: {
        summary: "Functions package up reusable logic and hand back a result with return.",
        details: [
          "`function add(a, b) { ... }` defines a function named `add` that takes two inputs (parameters) `a` and `b`. Nothing runs until you actually call it, like `add(3, 7)`.",
          "`return` is what sends a value back out of the function to whoever called it. Once `return` runs, the function stops immediately — code written after it never executes.",
          "A function with no `return` statement implicitly gives back `undefined`. Forgetting `return` is one of the most common beginner bugs — the function runs fine but the caller gets nothing useful.",
        ],
        example: 'function multiply(a, b) {\n  return a * b;\n}\nconsole.log(multiply(4, 5)); // 20',
      },
    },
    {
      id: 3,
      title: "Array Length",
      filename: "lesson3.js",
      objective: "Use the correct array property to loop through all fruits and log each one",
      preview: ["apple", "banana", "cherry"],
      difficulty: "easy",
      codeLines: [
        'const fruits = ["apple", "banana", "cherry"];',
        "",
        "for (let i = 0; i < fruits.{{zone1}}; i++) {",
        "  console.log(fruits[i]);",
        "}",
      ],
      zones: [{ id: "zone1", answer: "length" }],
      blocks: [
        { id: "b1", code: "length" },
        { id: "b2", code: "size" },
        { id: "b3", code: "count" },
        { id: "b4", code: "total" },
      ],
      wormIntro:
        "Arrays have a special property that tells you how many items they contain. Which one is it? Drag it into the slot after the dot!",
      wormCorrectAll: "Yes! .length gives us 3, so the loop runs from 0 to 2 and visits every fruit! 🍎🍌🍒",
      concept: {
        summary: "`.length` tells you how many items are in an array, which is what makes a for loop able to visit every one.",
        details: [
          "Arrays are ordered lists: `fruits[0]` is the first item, `fruits[1]` the second, and so on. `fruits.length` is a live count — it updates automatically if you add or remove items.",
          "The classic `for (let i = 0; i < fruits.length; i++)` loop starts `i` at 0 and keeps going while `i` is still less than the length, which is exactly the range of valid index positions.",
          "A very common bug is using `<=` instead of `<` — that runs one iteration too many and tries to read `fruits[3]` on a 3-item array, which doesn't exist and gives `undefined`.",
        ],
        example: 'const colors = ["red", "green", "blue"];\nconsole.log(colors.length); // 3\nconsole.log(colors[colors.length - 1]); // "blue" (last item)',
      },
    },
    {
      id: 4,
      title: "Array Methods",
      filename: "lesson4.js",
      difficulty: "medium",
      objective: "Use the right array method to create a new array with each number doubled",
      preview: ["[2, 4, 6, 8, 10]"],
      codeLines: [
        "const nums = [1, 2, 3, 4, 5];",
        "const doubled = nums.{{zone1}}(n => n * 2);",
        "",
        "console.log(doubled);",
        "// [2, 4, 6, 8, 10]",
      ],
      zones: [{ id: "zone1", answer: "map" }],
      blocks: [
        { id: "b1", code: "map" },
        { id: "b2", code: "filter" },
        { id: "b3", code: "reduce" },
        { id: "b4", code: "forEach" },
      ],
      wormIntro:
        "I need to TRANSFORM every number in the array into a new one! Which array method creates a NEW array with each element transformed? Think 🗺️!",
      wormCorrectAll: "Brilliant! .map() transforms each element and returns a brand new array! You're a natural coder! 🗺️✨",
      concept: {
        summary: "`.map()` transforms every item in an array and returns a brand new array — it never changes the original.",
        details: [
          "`nums.map(n => n * 2)` runs the function `n => n * 2` once per item and collects the results into a new array. The original `nums` array is untouched.",
          "Its cousins do different jobs: `.filter(fn)` keeps only the items where `fn` returns true (shrinking the array, not transforming it), and `.reduce(fn, start)` combines every item down into a single value, like a total.",
          "Because `.map()` always returns an array the same length as the input, it's the right tool whenever you want 'the same list, but each item changed' — not when you want to remove or combine items.",
        ],
        example: 'const names = ["ana", "bo"];\nconst shouted = names.map(n => n.toUpperCase());\nconsole.log(shouted); // ["ANA", "BO"]',
      },
    },
    {
      id: 5,
      title: "Conditionals",
      filename: "lesson5.js",
      difficulty: "medium",
      objective: "Add the right comparison operator to check if age is 18 OR older",
      preview: ['"You can vote!"', '"Too young"'],
      codeLines: [
        "function checkAge(age) {",
        "  if (age {{zone1}} 18) {",
        '    return "You can vote!";',
        "  }",
        '  return "Too young";',
        "}",
        "",
        'console.log(checkAge(20)); // "You can vote!"',
        'console.log(checkAge(15)); // "Too young"',
      ],
      zones: [{ id: "zone1", answer: ">=" }],
      blocks: [
        { id: "b1", code: ">=" },
        { id: "b2", code: "<=" },
        { id: "b3", code: "===" },
        { id: "b4", code: "!==" },
        { id: "b5", code: ">" },
      ],
      wormIntro:
        'The condition should be true when age is 18 OR older! Which comparison operator means "greater than OR equal to"? Not just greater than — equal counts too!',
      wormCorrectAll:
        "You did it! >= means greater than OR equal to, so 18 still passes! Beginner levels done — ready for something tougher? 🏆",
      concept: {
        summary: "Comparison operators (>=, <=, ===, !==) turn a question into true or false, which `if` then acts on.",
        details: [
          "`>=` means \"greater than or equal to\" and `<=` means \"less than or equal to\" — both include the boundary value itself, unlike plain `>` or `<`.",
          "`===` checks that two values are strictly equal (same value AND same type), and `!==` checks that they're strictly not equal. Prefer these over `==`/`!=`, which silently convert types before comparing and can produce surprising results like `\"5\" == 5` being true.",
          "An `if` block only runs its body when the condition evaluates to `true`. Once a `return` inside it fires, the function exits immediately — the code after the `if` never runs for that case.",
        ],
        example: 'function canRent(age) {\n  if (age >= 25) return true;\n  return false;\n}\nconsole.log(canRent(25)); // true — 25 counts as >= 25',
      },
    },
    {
      id: 6,
      title: "Closures",
      filename: "lesson6.js",
      difficulty: "hard",
      objective: "Complete the closure so each call to counter() increases and returns the running count",
      preview: ["1", "2"],
      codeLines: [
        "function makeCounter() {",
        "  let count = 0;",
        "  return function () {",
        "    count {{zone1}} 1;",
        "    return count;",
        "  };",
        "}",
        "",
        "const counter = makeCounter();",
        "console.log(counter()); // 1",
        "console.log(counter()); // 2",
      ],
      zones: [{ id: "zone1", answer: "+=" }],
      blocks: [
        { id: "b1", code: "+=" },
        { id: "b2", code: "=" },
        { id: "b3", code: "==" },
        { id: "b4", code: "*=" },
      ],
      wormIntro:
        "This inner function needs to REMEMBER and increase count every time it's called — that's a closure! Which operator adds 1 and saves the new value back into count?",
      wormCorrectAll:
        "Yes! += adds 1 to count and reassigns it — and because it's a closure, count survives between calls! You just built a stateful counter! 🔒✨",
      concept: {
        summary:
          "A closure lets an inner function remember variables from the outer function that created it, even after that outer function has returned.",
        details: [
          "makeCounter() runs once and returns a NEW function — but that returned function keeps a private link back to count, the variable from its enclosing scope. Every time you call counter(), it's still working with that same remembered count, not a fresh one.",
          "This is different from a normal function whose local variables are wiped clean every call. Closures are how JavaScript builds things like private state, memoized functions, and event handlers that remember data — without any object or class needed.",
          "+= is shorthand for count = count + 1 — reassigning inside the closure works because the inner function has real read/write access to the outer variable, not just a copy of its value.",
        ],
        example:
          'function makeAdder(start) {\n  let total = start;\n  return (n) => {\n    total += n;\n    return total;\n  };\n}\nconst add = makeAdder(10);\nadd(5); // 15\nadd(5); // 20',
      },
    },
    {
      id: 7,
      title: "Destructuring in Callbacks",
      filename: "lesson7.js",
      difficulty: "hard",
      objective:
        "Choose the array method that collapses the list into one total, then destructure each student object to pull out just the score",
      preview: ["170"],
      codeLines: [
        "const students = [",
        '  { name: "Ana", score: 80 },',
        '  { name: "Bo", score: 90 },',
        "];",
        "",
        "const total = students.{{zone1}}((sum, {{zone2}}) => sum + score, 0);",
        "console.log(total); // 170",
      ],
      // Two independent decisions on the same line — which method accumulates a single running
      // value, and how to destructure the callback's parameter — rather than one blank per line.
      zones: [
        { id: "zone1", answer: "reduce" },
        { id: "zone2", answer: "{ score }" },
      ],
      blocks: [
        { id: "b1", code: "reduce" },
        { id: "b2", code: "map" },
        { id: "b3", code: "filter" },
        { id: "b4", code: "forEach" },
        { id: "b5", code: "{ score }" },
        { id: "b6", code: "score" },
        { id: "b7", code: "{ name }" },
        { id: "b8", code: "student" },
      ],
      wormIntro:
        "Two blanks this time! First: which array method collapses a whole list down into one single running total? Second: destructure the callback's parameter to grab just the score property directly.",
      wormCorrectAll:
        "Exactly! reduce() collapses the array into one running total, and { score } pulls the score property straight out of each student object as you receive it — no need for student.score everywhere! Real problems often stack two decisions like this in one line. 🎯",
      concept: {
        summary:
          "You can destructure directly inside a function's parameter list, not just in a separate assignment — pulling out just the properties you need. Picking the right array method matters just as much as the destructuring itself.",
        details: [
          "map() and filter() both return a new array the same general shape as the input — neither can collapse a list down into one single value. reduce() is the one built for exactly that: it walks the array carrying an accumulator (sum here) forward from each call to the next, ending with one final result.",
          "({ score }) as a parameter is shorthand for \"this argument is an object — immediately unpack its score property into a variable called score.\" It's the same destructuring syntax as const { score } = student, just written inline where the parameter would normally go.",
          "This combination is extremely common in real code: reduce() (or map()/filter()) receiving a full object per callback call, destructured in the parameter list so the callback body never has to write student.score repeatedly.",
          "You can rename while destructuring too: ({ score: points }) would let you use points instead of score inside the function, useful when the property name already means something else in scope.",
        ],
        example:
          'const users = [{ name: "Ana", age: 25 }, { name: "Bo", age: 30 }];\nconst names = users.map(({ name }) => name);\n// ["Ana", "Bo"]',
      },
    },
    {
      id: 8,
      title: "Objects",
      filename: "lesson8.js",
      difficulty: "medium",
      objective: "Access the user's name property using dot notation",
      preview: ["Ada"],
      codeLines: ["const user = { name: \"Ada\", age: 30 };", "console.log(user.{{zone1}});"],
      zones: [{ id: "zone1", answer: "name" }],
      blocks: [
        { id: "b1", code: "name" },
        { id: "b2", code: "user" },
        { id: "b3", code: "key" },
        { id: "b4", code: "value" },
      ],
      wormIntro: "Objects store data as key-value pairs. Which property holds the user's name?",
      wormCorrectAll: "user.name reads the name property directly! Objects are everywhere in JS — get comfortable with dot notation!",
      concept: {
        summary: "Dot notation (object.property) reads a value stored on an object by its key.",
        details: [
          "An object like { name: \"Ada\", age: 30 } groups related data under named keys. user.name reads the value stored at the \"name\" key — as long as the key is a valid identifier, dot notation is the cleanest way to access it.",
          'Bracket notation (user["name"]) does the same thing but works even when the key isn\'t a valid identifier, or when the key is stored in a variable: const key = "name"; user[key] works, but user.key would look for a literal property called "key".',
          "Accessing a property that doesn't exist returns undefined rather than throwing an error — user.email on this object is undefined, not a crash.",
        ],
        example: 'const car = { brand: "Toyota", year: 2020 };\nconsole.log(car.brand); // "Toyota"\nconsole.log(car.color); // undefined',
      },
    },
    {
      id: 9,
      title: "Loops",
      filename: "lesson9.js",
      difficulty: "medium",
      objective: "Complete the for...of loop to print each color",
      preview: ["red", "green", "blue"],
      codeLines: ['const colors = ["red", "green", "blue"];', "for (const color {{zone1}} colors) {", "  console.log(color);", "}"],
      zones: [{ id: "zone1", answer: "of" }],
      blocks: [
        { id: "b1", code: "of" },
        { id: "b2", code: "in" },
        { id: "b3", code: "to" },
        { id: "b4", code: "=" },
      ],
      wormIntro: "for...of loops directly over an array's VALUES. Which keyword completes it?",
      wormCorrectAll: "for...of gives you each value directly — no index needed! Perfect for looping over arrays!",
      concept: {
        summary: "for...of loops directly over the values of an iterable (arrays, strings, and more), without needing an index.",
        details: [
          "for (const color of colors) visits each item in colors one at a time, binding it to color — much more direct than the classic for (let i = 0; i < colors.length; i++) + colors[i] pattern.",
          "Don't confuse it with for...in, which loops over an object's KEYS (or an array's indexes as strings) — for...of gives you values, for...in gives you keys. Using for...in on an array is almost always a mistake.",
          "for...of works on any iterable, not just arrays — strings, Maps, Sets, and more all support it.",
        ],
        example: 'for (const char of "hi") {\n  console.log(char);\n}\n// "h"\n// "i"',
      },
    },
    {
      id: 10,
      title: "Template Literals",
      filename: "lesson10.js",
      difficulty: "medium",
      objective: "Complete the template literal to interpolate the age variable",
      preview: ['"Ada is 30 years old"'],
      codeLines: [
        'const name = "Ada";',
        "const age = 30;",
        "const bio = `${name} is {{zone1}} years old`;",
        "console.log(bio);",
      ],
      zones: [{ id: "zone1", answer: "${age}" }],
      blocks: [
        { id: "b1", code: "${age}" },
        { id: "b2", code: "age" },
        { id: "b3", code: "{age}" },
        { id: "b4", code: "$age" },
      ],
      wormIntro: "Template literals use ${} to embed a variable's value directly into a string. Which block correctly interpolates age?",
      wormCorrectAll: "${age} evaluates age and drops it right into the string! Much cleaner than + concatenation!",
      concept: {
        summary: "Template literals (backtick strings) let you embed any expression directly inside a string using ${}.",
        details: [
          "`${name} is ${age} years old` — the backticks (not quotes) enable this. Anything inside ${} is evaluated as a real JavaScript expression and converted to a string, then spliced into place.",
          'Before template literals, the same string required concatenation: name + " is " + age + " years old" — readable for short strings, but gets messy fast with more variables or extra formatting.',
          "Template literals also support real multi-line strings without needing \\n — a backtick string can span multiple lines exactly as typed.",
        ],
        example: 'const price = 19.99;\nconsole.log(`Total: $${price * 2}`); // "Total: $39.98"',
      },
    },
    {
      id: 11,
      title: "Error Handling",
      filename: "lesson11.js",
      difficulty: "hard",
      objective: "Complete the try/catch so a parsing failure returns null instead of crashing",
      preview: ["42", "null"],
      codeLines: [
        "function parseNumber(str) {",
        "  try {",
        "    return JSON.parse(str);",
        "  {{zone1}} (err) {",
        "    return null;",
        "  }",
        "}",
        "",
        'console.log(parseNumber("42"));      // 42',
        'console.log(parseNumber("invalid")); // null',
      ],
      zones: [{ id: "zone1", answer: "catch" }],
      blocks: [
        { id: "b1", code: "catch" },
        { id: "b2", code: "except" },
        { id: "b3", code: "error" },
        { id: "b4", code: "finally" },
      ],
      wormIntro: "Code that might fail goes in try. Which keyword catches the error if it throws?",
      wormCorrectAll:
        "catch (err) runs only if something inside try throws — now bad input returns null instead of crashing the whole program! You've completed the JavaScript track! 🏆🎊",
      concept: {
        summary: "try/catch lets you run code that might fail without crashing the whole program.",
        details: [
          "Code inside try runs normally until something throws — the moment that happens, execution jumps straight into catch (err), skipping the rest of the try block entirely. err holds the actual error object that was thrown.",
          '`JSON.parse("invalid")` throws a SyntaxError because "invalid" isn\'t valid JSON — without a try/catch around it, that error would crash the whole program instead of being handled gracefully.',
          "finally (not used here) runs a block of cleanup code whether or not an error occurred — common for closing a connection or resetting UI state no matter how the try block turned out.",
        ],
        example: 'try {\n  undefinedFunction();\n} catch (err) {\n  console.log("Caught:", err.message);\n}',
      },
    },
  ],
};
