import type { Track } from "./types";

export const pythonTrack: Track = {
  id: "python",
  title: "Python",
  description: "Variables, functions, lists, and conditionals — the fundamentals of Python.",
  color: "#3776ab",
  levels: [
    {
      id: 1,
      title: "Variables",
      filename: "lesson1.py",
      difficulty: "easy",
      objective: 'Assign values to the variables so the program outputs "Hello World 42"',
      preview: ["Hello World 42"],
      codeLines: [
        "# Variables store data values",
        "message = {{zone1}}",
        "count = {{zone2}}",
        "",
        "print(message, count)",
      ],
      zones: [
        { id: "zone1", answer: '"Hello World"' },
        { id: "zone2", answer: "42" },
      ],
      blocks: [
        { id: "b1", code: '"Hello World"' },
        { id: "b2", code: "42" },
        { id: "b3", code: "True" },
        { id: "b4", code: "None" },
        { id: "b5", code: "[]" },
      ],
      wormIntro:
        "Hi! I'm Debug the worm! 🐛 Drag the correct values into the empty slots to assign the variables. message should be a string, count should be a number!",
      wormCorrectAll: "Amazing! You assigned both variables correctly! Let's move to the next challenge! 🎉",
      concept: {
        summary: "Python variables need no keyword and no declared type — just a name, `=`, and a value.",
        details: [
          "`message = \"Hello World\"` stores text (a string, in quotes); `count = 42` stores a number. No `let` or `var` needed — the `=` sign alone creates the variable.",
          "Python figures out the type from the value itself: strings, numbers, booleans (`True`/`False`, capitalized), and `None` (Python's version of \"nothing\") are all assigned the same way.",
          "Unlike JavaScript, Python cares about indentation, not curly braces, to know what's inside a block — you'll see this matter a lot starting with functions and `if` statements.",
        ],
        example: 'pi = 3.14\nname = "Ada"\nis_ready = True\nprint(name, pi, is_ready)',
      },
    },
    {
      id: 2,
      title: "Functions",
      filename: "lesson2.py",
      difficulty: "easy",
      objective: 'Complete the "add" function so it returns the sum of a and b (should output 10)',
      preview: ["10"],
      codeLines: ["def add(a, b):", "    return {{zone1}}", "", "result = add(3, 7)", "print(result)  # 10"],
      zones: [{ id: "zone1", answer: "a + b" }],
      blocks: [
        { id: "b1", code: "a + b" },
        { id: "b2", code: "a - b" },
        { id: "b3", code: "a * b" },
        { id: "b4", code: "a / b" },
      ],
      wormIntro:
        "This function should ADD two numbers together! Drag the expression that represents their sum into the return slot. What operation combines two values?",
      wormCorrectAll: "Perfect! a + b adds both parameters together! You're getting it! 🚀",
      concept: {
        summary: "def defines a function; indentation (not braces) marks what's inside it.",
        details: [
          "`def add(a, b):` starts a function named `add` taking parameters `a` and `b`. Everything indented underneath the colon is the function's body — Python uses that indentation instead of `{ }` to know where the function ends.",
          "`return` sends a value back to whoever called the function and immediately stops it, exactly like JavaScript. A function with no `return` gives back `None` automatically.",
          "Calling `add(3, 7)` doesn't print anything by itself — you have to capture the result (`result = add(3, 7)`) or wrap the call in `print()` to actually see it.",
        ],
        example: 'def multiply(a, b):\n    return a * b\n\nprint(multiply(4, 5))  # 20',
      },
    },
    {
      id: 3,
      title: "List Length",
      filename: "lesson3.py",
      difficulty: "easy",
      objective: "Use the correct built-in function to loop through all fruits and print each one",
      preview: ["apple", "banana", "cherry"],
      codeLines: [
        'fruits = ["apple", "banana", "cherry"]',
        "",
        "for i in range({{zone1}}(fruits)):",
        "    print(fruits[i])",
      ],
      zones: [{ id: "zone1", answer: "len" }],
      blocks: [
        { id: "b1", code: "len" },
        { id: "b2", code: "size" },
        { id: "b3", code: "count" },
        { id: "b4", code: "total" },
      ],
      wormIntro:
        "Python has a built-in function that tells you how many items are in a list. Which one is it? Drag it in front of the parentheses!",
      wormCorrectAll: "Yes! len(fruits) gives us 3, so the loop runs from 0 to 2 and visits every fruit! 🍎🍌🍒",
      concept: {
        summary: "len() counts the items in a list, string, or other collection.",
        details: [
          "`len(fruits)` returns how many items are in the `fruits` list. `range(len(fruits))` then produces the sequence `0, 1, 2` — exactly the valid index positions — for the loop to walk through.",
          "In real Python, `for fruit in fruits:` (looping directly over the items) is usually cleaner than looping over indexes when you don't actually need the index number. You'll see both patterns; this level teaches the index-based one because it mirrors how loops work in most other languages too.",
          "`len()` isn't just for lists — it works on strings (`len(\"hello\")` is 5) and other collections too, which makes it one of Python's most-used built-ins.",
        ],
        example: 'nums = [10, 20, 30, 40]\nprint(len(nums))  # 4\nfor n in nums:\n    print(n)  # loop directly over items, no index needed',
      },
    },
    {
      id: 4,
      title: "List Comprehensions",
      filename: "lesson4.py",
      difficulty: "medium",
      objective: "Complete the list comprehension so it doubles every number",
      preview: ["[2, 4, 6, 8, 10]"],
      codeLines: [
        "nums = [1, 2, 3, 4, 5]",
        "doubled = [n {{zone1}} 2 for n in nums]",
        "",
        "print(doubled)",
        "# [2, 4, 6, 8, 10]",
      ],
      zones: [{ id: "zone1", answer: "*" }],
      blocks: [
        { id: "b1", code: "*" },
        { id: "b2", code: "+" },
        { id: "b3", code: "-" },
        { id: "b4", code: "/" },
      ],
      wormIntro:
        "I need to DOUBLE every number in the list! Which operator multiplies a value? Drag it between n and 2! ✖️",
      wormCorrectAll: "Brilliant! n * 2 doubles each element as the list comprehension builds the new list! 🐍✨",
      concept: {
        summary: "A list comprehension builds a new list in one line: `[expression for item in list]`.",
        details: [
          "`[n * 2 for n in nums]` reads almost like English: \"for each `n` in `nums`, put `n * 2` in the new list.\" It's Python's compact equivalent of JavaScript's `.map()`.",
          "You can filter while building by adding a condition at the end, like `[n for n in nums if n > 2]`, which only keeps items where the condition is true — no separate `.filter()` call needed.",
          "Comprehensions are popular in Python because they're often more readable than an equivalent `for` loop with `.append()` calls, but for very complex logic, a plain loop can still be clearer — reach for whichever reads better.",
        ],
        example: 'nums = [1, 2, 3, 4]\nsquares = [n * n for n in nums]\nprint(squares)  # [1, 4, 9, 16]',
      },
    },
    {
      id: 5,
      title: "Conditionals",
      filename: "lesson5.py",
      difficulty: "medium",
      objective: "Add the right comparison operator to check if age is 18 OR older",
      preview: ['"You can vote!"', '"Too young"'],
      codeLines: [
        "def check_age(age):",
        "    if age {{zone1}} 18:",
        '        return "You can vote!"',
        '    return "Too young"',
        "",
        'print(check_age(20))  # "You can vote!"',
        'print(check_age(15))  # "Too young"',
      ],
      zones: [{ id: "zone1", answer: ">=" }],
      blocks: [
        { id: "b1", code: ">=" },
        { id: "b2", code: "<=" },
        { id: "b3", code: "==" },
        { id: "b4", code: "!=" },
        { id: "b5", code: ">" },
      ],
      wormIntro:
        'The condition should be true when age is 18 OR older! Which comparison operator means "greater than OR equal to"? Not just greater than — equal counts too!',
      wormCorrectAll:
        "You did it! >= means greater than OR equal to, so 18 still passes! Beginner levels done — ready for something tougher? 🏆",
      concept: {
        summary: "Comparison operators (>=, <=, ==, !=) turn a question into True or False, which `if` acts on.",
        details: [
          "`>=` means \"greater than or equal to\" and `<=` means \"less than or equal to\" — both include the boundary value, unlike plain `>` or `<`.",
          "Python uses `==` to check if two values are equal and `!=` to check if they're not — no `===` here, since Python doesn't do the silent type-juggling JavaScript's `==` does, so a plain `==` is already safe.",
          "`if condition:` only runs its indented body when the condition is `True`. A `return` inside it exits the function immediately, so any code after the `if` block is skipped for that case.",
        ],
        example: 'def can_rent(age):\n    if age >= 25:\n        return True\n    return False\n\nprint(can_rent(25))  # True — 25 counts as >= 25',
      },
    },
    {
      id: 6,
      title: "Dictionaries",
      filename: "lesson6.py",
      difficulty: "medium",
      objective: "Access the user's name from the dictionary using the correct key",
      preview: ["Ada"],
      codeLines: ['user = {"name": "Ada", "age": 30}', "name = user[{{zone1}}]", "print(name)"],
      zones: [{ id: "zone1", answer: '"name"' }],
      blocks: [
        { id: "b1", code: '"name"' },
        { id: "b2", code: "name" },
        { id: "b3", code: "'user'" },
        { id: "b4", code: "0" },
      ],
      wormIntro: "Dictionaries are accessed with square brackets and the key. Which block is the correct key to get the name?",
      wormCorrectAll: 'user["name"] reads the value stored at that key! Dictionaries are Python\'s key-value powerhouse!',
      concept: {
        summary: "Square-bracket key access (dict[key]) reads a value from a dictionary by its key.",
        details: [
          'user["name"] looks up the value stored under the "name" key — the key must match exactly, including type: "name" (a string) and name (a variable) are very different things, and using the wrong one is a common beginner mix-up.',
          "Unlike a list, a dictionary's items aren't accessed by position — there's no user[0] unless 0 is literally one of the keys. Order of insertion is preserved in modern Python, but you still access by key, not index.",
          'Accessing a key that doesn\'t exist raises a KeyError and crashes — use .get("key", default) instead when you\'re not sure a key exists.',
        ],
        example: 'car = {"brand": "Toyota", "year": 2020}\nprint(car["brand"])  # "Toyota"',
      },
    },
    {
      id: 7,
      title: "Loops",
      filename: "lesson7.py",
      difficulty: "medium",
      objective: "Complete the for loop to print each fruit",
      preview: ["apple", "banana", "cherry"],
      codeLines: ['fruits = ["apple", "banana", "cherry"]', "for fruit {{zone1}} fruits:", "    print(fruit)"],
      zones: [{ id: "zone1", answer: "in" }],
      blocks: [
        { id: "b1", code: "in" },
        { id: "b2", code: "of" },
        { id: "b3", code: "on" },
        { id: "b4", code: "=" },
      ],
      wormIntro: 'Python\'s for loop uses a specific keyword to say "for each item in this collection". Which one?',
      wormCorrectAll: "for fruit in fruits — Python's for loop always uses 'in', unlike JavaScript's for...of!",
      concept: {
        summary: "Python's for loop always uses in to iterate directly over a collection's items.",
        details: [
          "for fruit in fruits: visits each item in fruits one at a time, binding it to fruit — there's no separate \"for...of\" vs \"for...in\" distinction like JavaScript; Python just uses in for both lists and, differently, dictionary keys.",
          "Looping over a dictionary with for key in my_dict: gives you the keys by default — use my_dict.items() (covered in the Dictionaries section) to get both key and value together.",
          "range(n) is what you reach for when you need a plain sequence of numbers instead of looping over an existing collection: for i in range(5).",
        ],
        example: 'for letter in "abc":\n    print(letter)\n# a\n# b\n# c',
      },
    },
    {
      id: 8,
      title: "f-strings",
      filename: "lesson8.py",
      difficulty: "medium",
      objective: "Complete the f-string to interpolate the age variable",
      preview: ['"Ada is 30 years old"'],
      codeLines: ['name = "Ada"', "age = 30", 'bio = f"{name} is {{zone1}} years old"', "print(bio)"],
      zones: [{ id: "zone1", answer: "{age}" }],
      blocks: [
        { id: "b1", code: "{age}" },
        { id: "b2", code: "age" },
        { id: "b3", code: "${age}" },
        { id: "b4", code: "(age)" },
      ],
      wormIntro: "f-strings use curly braces to embed a variable directly into a string. Which block correctly interpolates age?",
      wormCorrectAll: "{age} inside an f-string evaluates age and drops it right in! Note: no dollar sign needed, that's JavaScript's syntax!",
      concept: {
        summary: "f-strings (prefixed with f) let you embed any expression directly inside a string using curly braces.",
        details: [
          'f"{name} is {age} years old" — the f prefix before the opening quote enables this. Anything inside {} is evaluated as a real Python expression and converted to a string, then spliced into place.',
          "This is a common trip-up for JavaScript developers: Python's f-strings use bare {expression}, not JavaScript's ${expression} — the dollar sign isn't part of Python's syntax at all.",
          'f-strings can format the interpolated value too: f"{price:.2f}" formats a number to two decimal places in the same breath, without a separate formatting call.',
        ],
        example: 'price = 19.99\nprint(f"Total: ${price * 2:.2f}")  # "Total: $39.98"',
      },
    },
    {
      id: 9,
      title: "Error Handling",
      filename: "lesson9.py",
      difficulty: "hard",
      objective:
        "Complete the try/except keyword AND name the specific exception type so a parsing failure returns None instead of crashing",
      preview: ["42", "None"],
      codeLines: [
        "def parse_number(text):",
        "    try:",
        "        return int(text)",
        "    {{zone1}} {{zone2}}:",
        "        return None",
        "",
        'print(parse_number("42"))      # 42',
        'print(parse_number("invalid")) # None',
      ],
      // Two independent decisions on the same line — the syntax keyword, and which specific
      // exception type int() actually raises — rather than one blank per line.
      zones: [
        { id: "zone1", answer: "except" },
        { id: "zone2", answer: "ValueError" },
      ],
      blocks: [
        { id: "b1", code: "except" },
        { id: "b2", code: "catch" },
        { id: "b3", code: "error" },
        { id: "b4", code: "finally" },
        { id: "b5", code: "ValueError" },
        { id: "b6", code: "TypeError" },
        { id: "b7", code: "KeyError" },
        { id: "b8", code: "Exception" },
      ],
      wormIntro:
        "Two blanks this time! First: which keyword catches an error if it raises? Second: int(\"invalid\") raises a specific kind of error — which one?",
      wormCorrectAll:
        "except ValueError: — the right keyword AND the exact error type int() raises on bad input! Now bad input returns None instead of crashing. You've completed the Python track! 🏆🎊",
      concept: {
        summary: "try/except lets you run code that might fail without crashing the whole program — and naming the right exception type matters, not just the syntax.",
        details: [
          "Code inside try runs normally until something raises — the moment that happens, execution jumps straight into except, skipping the rest of the try block. except ValueError specifically catches ValueErrors, letting other, unexpected error types still crash loudly instead of being silently swallowed.",
          'int("invalid") raises a ValueError specifically, because "invalid" can\'t be converted to an integer — TypeError, KeyError, and the others are real Python exceptions too, just not the one this particular call actually raises. Catching the exact type you expect (rather than a bare except:) is what keeps genuinely unexpected bugs from getting silently hidden.',
          "Python spells this except, not JavaScript's catch — a common slip when switching between the two languages.",
        ],
        example: 'try:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    print("Cannot divide by zero")',
      },
    },
  ],
};
